#!/usr/bin/env bash

KEYFILE="gocryptfs.key"
ENCRYPTED_KEYFILE="gocryptfs.key.age"
ENCRYPTED_DIR="encrypted"
PLAIN_DIR="plain"
ENCRYPTED_RECIPIENTS_FILE="${PLAIN_DIR}/recipients.txt"
# REVERSE_CONFIG_FILE="${ENCRYPTED_DIR}/gocryptfs-reverse.conf"

if [ -f ~/.ssh/id_ed25519 ]; then
	USER_PRIVATE_KEY=~/.ssh/id_ed25519
	USER_PUBLIC_KEY=~/.ssh/id_ed25519.pub
else
	USER_PRIVATE_KEY=~/.ssh/id_rsa
	USER_PUBLIC_KEY=~/.ssh/id_rsa.pub
fi

echo "Initializing encrypted directory and creating keyfile..."
mkdir -p "$ENCRYPTED_DIR" "$PLAIN_DIR"
dd if=/dev/urandom bs=32 count=1 of="$KEYFILE"
if gocryptfs -reverse -config "$REVERSE_CONFIG_FILE" -init "$PLAIN_DIR" -passfile "$KEYFILE" &&
	age -R "$USER_PUBLIC_KEY" -a -o "$ENCRYPTED_KEYFILE" "$KEYFILE" &&
	rm -f "$KEYFILE" &&
	age -d -i "$USER_PRIVATE_KEY" -o - "$ENCRYPTED_KEYFILE" | gocryptfs -config "$REVERSE_CONFIG_FILE" -reverse "$PLAIN_DIR" "$ENCRYPTED_DIR"; then
	cat "$USER_PUBLIC_KEY" >"$ENCRYPTED_RECIPIENTS_FILE"
	echo -e "\nDecrypted folder mounted to \"$PLAIN_DIR\""
	echo -e "You can check the list of recipients who can decrypt it in \"$ENCRYPTED_RECIPIENTS_FILE\""

else
	echo -e "\nFailed to decrypt the keyfile"
fi
